// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugFrame } from "./DebugFrame";

/**
 * Snapshot of evaluation state at a pause point, JSON-friendly.
 *
 * Secrets never leave the host process: we send the names only so the UI
 * can list them without leaking values into the renderer or any later
 * devtools capture.
 */
export type DebugScope = { 
/**
 * Named bindings, outer-most frame first, inner frames last (same
 * order they were pushed). Inner-frame bindings shadow outer ones at
 * lookup time — the UI is responsible for honoring that visually if
 * it wants to.
 */
bindings: Array<DebugFrame>, 
/**
 * Recipe inputs.
 */
inputs: Record<string, unknown>, 
/**
 * Secret *names* declared by the recipe. Values are never serialized.
 */
secrets: Array<string>, 
/**
 * Bare `$` current value, if any.
 */
current: unknown | null, 
/**
 * Per-type emit counts so far (cumulative).
 */
emit_counts: Record<string, number>, };
