// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a slug has any deployed version in the daemon. Carries the
 * latest version's metadata when present.
 */
export type DeployedState = { "kind": "none" } | { "kind": "deployed", version: number, deployed_at: number, };
