// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for one frozen deployed version of a recipe. The source
 * and catalog live on disk under `<daemon_dir>/deployments/<slug>/v<n>/`;
 * this is the row recorded in the daemon DB and the wire shape Studio
 * renders in its recipe-status surface.
 */
export type DeployedVersion = { slug: string, version: number, deployed_at: number, };
