// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticReport = { 
/**
 * How the run terminated. `"settled"` / `"completed"` is the happy
 * path; anything else is a clue.
 */
stall_reason: string | null, unmet_expectations: Array<string>, unfired_capture_rules: Array<string>, unmatched_captures: Array<string>, unhandled_affordances: Array<string>, };
