// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File classification rules (DESIGN_HANDOFF.md):
 *   `forage.toml`               → `Manifest`
 *   `<slug>/recipe.forage`      → `Recipe`
 *   `*.forage` at workspace root → `Declarations`
 *   `<slug>/fixtures/*.json`    → `Fixture`
 *   `<slug>/snapshot.json`      → `Snapshot`
 *   everything else             → `Other`
 */
export type FileKind = "recipe" | "declarations" | "fixture" | "snapshot" | "manifest" | "other";
