// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `forage.toml` shape. Every field declared without `#[serde(default)]`
 * is required on parse — a manifest that omits `description`,
 * `category`, or `tags` is malformed and fails to load. New
 * workspaces created in-code use the `Default` impl, which serialises
 * to a manifest where all required fields are present (with empty
 * string / empty list values); the round-trip succeeds because the
 * keys are emitted, just empty.
 */
export type Manifest = { 
/**
 * Publish slug — `"author/name"`. `None` until the workspace
 * becomes publishable.
 */
name: string | null, 
/**
 * One-line description shown in the hub listing. Required on
 * parse; the publish path enforces a non-empty value (per the
 * hub-api shape).
 */
description: string, 
/**
 * Hub category — matches the `category` segment on the listing
 * surface. Required on parse; lowercase kebab-case, validated
 * server-side.
 */
category: string, 
/**
 * Search tags. Required on parse; empty list when unset.
 */
tags: Array<string>, 
/**
 * Map from `"author/slug"` to integer hub version. Optional on
 * parse because a workspace without deps is common.
 */
deps: { [key in string]?: number }, };
