// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manifest = { 
/**
 * Publish slug — `"author/name"`. `None` until the workspace
 * becomes publishable.
 */
name: string | null, 
/**
 * Map from `"author/slug"` to integer hub version.
 */
deps: { [key in string]?: number }, };
