// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IterationPause } from "./IterationPause";
import type { StepPause } from "./StepPause";

/**
 * What the engine paused on. Wraps the two `forage-http` pause payloads
 * in a tagged union so the frontend can render either shape with one
 * event listener.
 */
export type PausePayload = { "kind": "step" } & StepPause | { "kind": "iteration" } & IterationPause;
