// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublishPreview = { recipe_bytes: bigint, base_version: number | null, decls_count: number, fixtures_count: number, };
