// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed error surface for `publish_recipe`. The stale-base variant
 * carries the version numbers the UI needs to render the rebase
 * prompt; other failures fall through `Other` with a message.
 *
 * Tauri serializes this as the JS-side discriminated union exported
 * through ts-rs.
 */
export type PublishError = { "kind": "stale_base", latest_version: number, your_base: number | null, message: string, } | { "kind": "not_signed_in", message: string, } | { "kind": "other", message: string, };
