// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One emitted record — a type name + the bound fields as plain JSON.
 *
 * On the TS side it's exported as `RecipeRecord` to avoid colliding
 * with the built-in `Record<K, V>` utility type — without the rename,
 * the generated file would self-reference and TypeScript would
 * resolve `Record<string, unknown>` to the local declaration.
 */
export type RecipeRecord = { typeName: string, fields: Record<string, unknown>, };
