// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepLocation } from "./StepLocation";

/**
 * Structural outline of a recipe — currently just step locations,
 * enough for Studio to anchor breakpoint glyphs and the "reveal paused
 * step" jump without re-implementing a parser in TypeScript. Extend
 * (types, emits, for-loops) as the UI needs them.
 */
export type RecipeOutline = { steps: Array<StepLocation>, };
