// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployedState } from "./DeployedState";
import type { DraftState } from "./DraftState";

/**
 * Per-slug status combining the Studio's on-disk view (drafts) with
 * the daemon's view (deployed versions). The frontend renders these
 * side by side so the user can see "edited but not deployed" or
 * "deployed but the draft is missing" without joining the two views
 * itself.
 */
export type RecipeStatus = { slug: string, draft: DraftState, deployed: DeployedState, };
