// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One emitted record — a synthetic `_id`, a type name, and the bound
 * fields as plain JSON.
 *
 * `_id` is assigned by the engine at emit time as a sequential string
 * (`rec-0`, `rec-1`, …) and is what `Ref<T>` field values point at. It
 * rides through the snapshot and serializes alongside the type-defined
 * fields so downstream consumers (Studio, the output store) can
 * resolve ref pointers without a side channel.
 *
 * On the TS side it's exported as `RecipeRecord` to avoid colliding
 * with the built-in `Record<K, V>` utility type — without the rename,
 * the generated file would self-reference and TypeScript would
 * resolve `Record<string, unknown>` to the local declaration.
 */
export type RecipeRecord = { _id: string, typeName: string, fields: Record<string, unknown>, };
