// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";

export type RunOutcome = { ok: boolean, snapshot: Snapshot | null, error: string | null, };
