// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";
import type { Trigger } from "./Trigger";

/**
 * One execution of a `Run`. Every fired run produces one row, success
 * or failure. Consumers chart `counts` and `outcome` over time.
 */
export type ScheduledRun = { 
/**
 * ULID.
 */
id: string, run_id: string, 
/**
 * When the run kicked off, ms since epoch.
 */
at: number, trigger: Trigger, outcome: Outcome, duration_s: number, 
/**
 * Emit counts grouped by record type name. BTreeMap so consumers
 * see consistent ordering across rows; serialized as a JSON object
 * in storage.
 */
counts: { [key in string]?: number }, 
/**
 * Number of validation issues (errors + warnings) the recipe
 * surfaced. Pure-error runs short-circuit before execution, so a
 * row with a non-zero `diagnostics` count and `outcome: Fail` is
 * the validation-blocked path; otherwise the count reflects
 * validation warnings the engine ran through.
 */
diagnostics: number, 
/**
 * Free-form failure reason. `None` on success. The diagnostic
 * report carries structured stall info; this is the
 * human-readable summary.
 */
stall: string | null, 
/**
 * Which deployed version the engine actually executed for this
 * row. `None` only for the no-deployment short-circuit failure
 * (where `stall == Some("recipe not deployed")`) and for the
 * synthetic cron-fail recorded before any version could be
 * resolved. Every other row — including engine-side failures —
 * carries the version the engine ran, so emit counts remain
 * interpretable across deploys.
 */
recipe_version: number | null, };
