// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StepLocation = { name: string, 
/**
 * 0-based line of the step declaration's start.
 */
start_line: number, start_col: number, end_line: number, end_col: number, };
