// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugScope } from "./DebugScope";

/**
 * Payload the engine sends to the debugger at a step pause.
 */
export type StepPause = { 
/**
 * Step name (`recipe.body[i].name`).
 */
step: string, 
/**
 * 0-based index of this step in the recipe's flat statement order.
 */
step_index: number, scope: DebugScope, };
