// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire view of the loaded `Workspace`. Carries the manifest summary
 * and the root path — the file list is served separately by
 * `list_workspace_files` so the UI can refetch the tree without
 * re-shipping the manifest on every poll.
 */
export type WorkspaceInfo = { root: string, 
/**
 * Publish slug from `forage.toml`, e.g. `"dima/cannabis"`.
 */
name: string | null, 
/**
 * `"author/slug"` → integer hub version. BTreeMap preserves
 * sorted iteration on the wire so consumers see deterministic
 * ordering.
 */
deps: { [key in string]?: number }, };
