// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeUnit } from "./TimeUnit";

/**
 * How often the daemon should fire a `Run`.
 */
export type Cadence = { "kind": "manual" } | { "kind": "interval", every_n: number, unit: TimeUnit, } | { "kind": "cron", expr: string, };
