// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daemon process status, surfaced to the Studio footer.
 */
export type DaemonStatus = { 
/**
 * True iff the scheduler task is alive. When false, the daemon is
 * still usable as an API surface (configure, trigger, list) but
 * scheduled cadences won't fire.
 */
running: boolean, version: string, 
/**
 * When the current scheduler task started, ms since epoch. 0 when
 * `running` is false.
 */
started_at: number, 
/**
 * Number of enabled, non-manual runs the scheduler is currently
 * tracking.
 */
active_count: number, };
