// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceStartOut = { device_code: string, user_code: string, verification_url: string, interval: bigint, expires_in: bigint, };
