// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeDiagnostic } from "./RuntimeDiagnostic";

export type DiagnosticReport = { 
/**
 * How the run terminated. `"settled"` / `"completed"` is the happy
 * path; anything else is a clue.
 */
stall_reason: RuntimeDiagnostic | null, unmet_expectations: Array<RuntimeDiagnostic>, unfired_capture_rules: Array<RuntimeDiagnostic>, unmatched_captures: Array<RuntimeDiagnostic>, unhandled_affordances: Array<RuntimeDiagnostic>, };
