// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One validation issue with a precise source location. Maps onto
 * Monaco's `IMarkerData` shape on the frontend so squigglies land
 * under the offending token instead of at line 1.
 */
export type Diagnostic = { severity: string, code: string, message: string, 
/**
 * 0-based line/column for the start of the span.
 */
start_line: number, start_col: number, 
/**
 * 0-based line/column for the end of the span (exclusive).
 */
end_line: number, end_col: number, };
