// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a slug has a draft on disk and whether that draft parses.
 * `Missing` covers the deployed-but-no-draft case: the daemon
 * remembers a slug we no longer have a source file for.
 */
export type DraftState = { "kind": "valid", path: string, } | { "kind": "broken", path: string, error: string, } | { "kind": "missing" };
