// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind";

/**
 * Recursive file-tree node returned by `list_workspace_files`. The
 * tree is rooted at the workspace root; each `File` carries a precise
 * `FileKind` classification so the UI can render the right affordance
 * (recipe -> open in editor, fixture -> open as JSON, etc.).
 */
export type FileNode = { "kind": "file", name: string, path: string, file_kind: FileKind, } | { "kind": "folder", name: string, path: string, children: Array<FileNode>, };
