// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-Run derived health label.
 *
 * `Ok`: latest run succeeded and emit counts are not drifting.
 * `Drift`: latest run succeeded but a record type's count fell ≥30%
 *   below the median of the prior 7 ok runs.
 * `Fail`: latest run failed.
 * `Paused`: Run.enabled is false. The daemon doesn't compute this from
 *   history — Studio sets it when the user toggles the run off.
 * `Unknown`: a freshly created run with no history yet, or the daemon
 *   hasn't observed it in this lifetime.
 */
export type Health = "ok" | "drift" | "fail" | "paused" | "unknown";
