// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Markdown hover payload for the word at (line, col), 0-based.
 */
export type HoverInfo = { markdown: string, };
