// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugScope } from "./DebugScope";

/**
 * Payload the engine sends to the debugger at a `for`-loop iteration
 * boundary. Fired immediately after `$<variable>` is bound to the
 * current item but before the loop body executes.
 */
export type IterationPause = { 
/**
 * Loop variable name from `for $<variable> in …`.
 */
variable: string, 
/**
 * 0-based index within the current `for` collection.
 */
iteration: number, 
/**
 * Total items in the current iteration's collection.
 */
total: number, scope: DebugScope, };
