// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the language's reserved word + transform inventory.
 * Studio fetches this once at startup so Monaco syntax highlighting,
 * completion, and any future linting all draw from the same canonical
 * lists in `forage-core`. No more hand-maintained TS arrays that
 * silently drift when the language gains a keyword.
 */
export type LanguageDictionary = { keywords: Array<string>, type_keywords: Array<string>, transforms: Array<string>, };
