// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `forage.toml` shape. Every field is optional at parse — the only
 * things a workspace must declare to open are nothing. Publish
 * metadata (description / category / tags) defaults to empty values
 * and is validated for non-emptiness at publish time, not at load
 * time. (The C3 audit fix made these required-on-parse; that conflated
 * "publish-ready" with "workspace-loadable" and broke every existing
 * workspace that pre-dates the schema change. See the followup
 * product plan: these fields probably want to move off the workspace
 * manifest and into per-recipe metadata, since each recipe in a
 * workspace can be published independently.)
 */
export type Manifest = { 
/**
 * Publish slug — `"author/name"`. `None` until the workspace
 * becomes publishable.
 */
name: string | null, 
/**
 * One-line description shown in the hub listing. Empty string
 * when unset; the publish path bails with a clear error if
 * empty at publish time.
 */
description: string, 
/**
 * Hub category — matches the `category` segment on the listing
 * surface. Empty string when unset; lowercase kebab-case,
 * validated server-side at publish time.
 */
category: string, 
/**
 * Search tags. Empty list when unset.
 */
tags: Array<string>, 
/**
 * Map from `"author/slug"` to integer hub version. Optional on
 * parse because a workspace without deps is common.
 */
deps: { [key in string]?: number }, };
