// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unit of work for one iteration of a recipe.
 *
 * `variable` is the loop variable's name (without leading `$`).
 * `None` means the unit is the whole recipe — only happens when no
 * `for` loop contains an `emit`.
 *
 * `types` lists the record types emitted inside the unit scope, in
 * source order. UIs typically use the first as the progress
 * denominator (they all share the same iteration count, modulo
 * conditional emits inside the scope).
 */
export type ProgressUnit = { variable: string | null, types: Array<string>, };
