// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the recents list. Captured at workspace-open time;
 * `recipe_count` is a cached integer so the Welcome view doesn't have
 * to scan every recent workspace's disk.
 */
export type RecentWorkspace = { path: string, name: string, 
/**
 * Milliseconds since the Unix epoch.
 */
opened_at: number, recipe_count: number, };
