// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the engine does after a debug pause.
 */
export type ResumeAction = "continue" | "step_over" | "stop";
