// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";
import type { Health } from "./Health";

/**
 * A scheduled recipe: the daemon's unit of recurring work.
 *
 * A `Run` is created on first explicit Run-live (auto-created via
 * `Daemon::ensure_run`) and configured (cadence, output path, enabled
 * flag) by the user through Studio. The daemon scheduler ticks against
 * `Run.cadence`; each tick produces a `ScheduledRun` record (success
 * *or* failure).
 */
export type Run = { 
/**
 * ULID — sortable, opaque, generated once at creation.
 */
id: string, recipe_slug: string, 
/**
 * Workspace the recipe lives in. The daemon is per-workspace, so
 * in practice this matches the daemon's `workspace_root`; carried
 * on the row so consumers can render context without a back-ref.
 */
workspace_root: string, enabled: boolean, cadence: Cadence, 
/**
 * Output store path — defaults to `<workspace_root>/.forage/data/<slug>.sqlite`.
 */
output: string, 
/**
 * Derived from the latest `ScheduledRun` plus the prior 7 ok runs.
 * See `health::derive_health`.
 */
health: Health, 
/**
 * Next time the scheduler will fire this run, ms since epoch.
 * `None` for `Cadence::Manual`.
 */
next_run: number | null, 
/**
 * Pointer to the deployed-recipe version the scheduler should
 * execute. `None` until the slug has been deployed at least once;
 * scheduled fires against a `None` pointer record a clean failure
 * rather than crashing, so the user can configure cadence before
 * the first deploy.
 */
deployed_version: number | null, };
