// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cadence } from "./Cadence";

/**
 * Configuration update payload for `Daemon::configure_run`.
 */
export type RunConfig = { cadence: Cadence, output: string, enabled: boolean, };
