// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";

export type RunOutcome = { ok: boolean, snapshot: Snapshot | null, error: string | null, 
/**
 * Non-fatal post-run daemon bookkeeping failure. The engine
 * succeeded but the Run row didn't make it into the daemon
 * sidebar — the UI surfaces this as a soft banner so the user
 * isn't left wondering why their recipe didn't show up.
 */
daemon_warning: string | null, };
