// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One diagnostic produced during a run. The message is the
 * human-readable explanation; `line` is the 0-based source line of the
 * recipe construct that produced it (e.g. an `expect` block, a step's
 * `browser { … }` config, or the step header for stalls), if the
 * caller had source access to resolve it.
 */
export type RuntimeDiagnostic = { message: string, line: number | null, };
