// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticReport } from "./DiagnosticReport";
import type { RecipeRecord } from "./RecipeRecord";

/**
 * Snapshot of a run: every emitted record, in emission order, plus
 * the diagnostic envelope.
 */
export type Snapshot = { records: Array<RecipeRecord>, diagnostic: DiagnosticReport, };
