// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";

export type ValidationOutcome = { ok: boolean, diagnostics: Array<Diagnostic>, };
