name = "forage-hub-api"
main = "src/index.ts"
compatibility_date = "2026-05-11"

routes = [
    { pattern = "api.foragelang.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "METADATA"
id = "9cb7039af7cd40f4a3e2dad24c6b32c8"

[[r2_buckets]]
binding = "BLOBS"
bucket_name = "forage-hub-blobs"
