// Helpers shared across the worker tests. Bring a user identity by
// signing a real JWT against the test signing key, and build canonical
// PublishRequest / ForkRequest payloads inline so each test stays
// readable.

import worker from '../src/index'
import type { Env, PublishRequest, ForkRequest } from '../src/types'
import { signAccessToken } from '../src/jwt'
import {
    env,
    reset,
    createExecutionContext,
    waitOnExecutionContext,
} from 'cloudflare:test'

// The pool's `env` is typed as `Cloudflare.Env` (generated by
// `wrangler types` from the bindings in `wrangler.toml`). Our worker's
// `Env` adds the OAuth + admin secrets exposed at test time through
// the vitest config; cast through `unknown` so the test code uses the
// full worker `Env` shape.
export const testEnv: Env = env as unknown as Env

// Mutate the R2-fallback threshold for a single test. Restored
// automatically by `resetStorage` (which wipes the env-var binding
// alongside KV/R2). Pass a byte count; subsequent putVersion calls
// during the same test use the override.
export function setR2FallbackThreshold(bytes: number): void {
    ;(testEnv as { R2_FALLBACK_THRESHOLD_BYTES?: string }).R2_FALLBACK_THRESHOLD_BYTES =
        String(bytes)
}

export function clearR2FallbackThreshold(): void {
    delete (testEnv as { R2_FALLBACK_THRESHOLD_BYTES?: string }).R2_FALLBACK_THRESHOLD_BYTES
}

// Wipe every binding's state. Use as `beforeEach(resetStorage)` to
// keep tests independent within a file (the pool isolates between
// files, not between individual tests).
export async function resetStorage(): Promise<void> {
    await reset()
}

// Sign an access token for a fake user. Matches what the OAuth flow
// would produce.
export async function userToken(login: string): Promise<string> {
    return signAccessToken(login, testEnv.JWT_SIGNING_KEY ?? 'test-jwt-signing-key')
}

// Convenience: dispatch a Request through the worker entry. The
// execution context is awaited so any deferred `ctx.waitUntil` work
// finishes before the test moves on.
export async function fetchWorker(request: Request): Promise<Response> {
    const ctx = createExecutionContext()
    const resp = await worker.fetch(request, testEnv)
    await waitOnExecutionContext(ctx)
    return resp
}

export async function fetchJson(request: Request): Promise<{ status: number; body: any }> {
    const resp = await fetchWorker(request)
    const text = await resp.text()
    const body = text.length > 0 ? JSON.parse(text) : null
    return { status: resp.status, body }
}

// Build a canonical PublishRequest body. The recipe's header name
// must equal the URL slug the publish posts to — the hub enforces
// this — so the helper takes the slug as a first argument and stamps
// it inside the recipe source. Pass `recipe:` in overrides to bypass
// the default for tests that exercise body-level recipe content
// (slug-mismatch tests, for instance).
export function publishRequest(
    slug: string,
    overrides: Partial<PublishRequest> = {},
): PublishRequest {
    return {
        description: 'Sample description',
        category: 'dispensary',
        tags: ['test'],
        recipe: `recipe "${slug}" {\n  step list { source = "https://example.com" }\n}\n`,
        decls: [],
        fixtures: [],
        snapshot: null,
        base_version: null,
        ...overrides,
    }
}

export function forkRequest(as: string | null = null): ForkRequest {
    return { as }
}

export function authedPostJson(
    url: string,
    token: string | null,
    body: unknown,
): Request {
    const headers: Record<string, string> = { 'Content-Type': 'application/json' }
    if (token !== null) headers.Authorization = `Bearer ${token}`
    return new Request(url, {
        method: 'POST',
        headers,
        body: JSON.stringify(body),
    })
}

export function authedDelete(url: string, token: string | null): Request {
    const headers: Record<string, string> = {}
    if (token !== null) headers.Authorization = `Bearer ${token}`
    return new Request(url, { method: 'DELETE', headers })
}

export function get(url: string): Request {
    return new Request(url, { method: 'GET' })
}
