//! `forage.toml` parse + serialize.
//!
//! Shape:
//!
//! ```toml
//! # optional — required for `forage publish`.
//! name = "dima/cannabis"
//!
//! [deps]
//! "dima/shared-types" = 3
//! ```
//!
//! The lockfile (`forage.lock`) reuses the same TOML wire format with a
//! `[deps]` table whose values are `{ version, hash }` records — see
//! `Lockfile` / `LockedDep` below.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use ts_rs::TS;

/// `forage.toml` shape. Every field is optional at parse — the only
/// things a workspace must declare to open are nothing. Publish
/// metadata (description / category / tags) defaults to empty values
/// and is validated for non-emptiness at publish time, not at load
/// time. (The C3 audit fix made these required-on-parse; that conflated
/// "publish-ready" with "workspace-loadable" and broke every existing
/// workspace that pre-dates the schema change. See the followup
/// product plan: these fields probably want to move off the workspace
/// manifest and into per-recipe metadata, since each recipe in a
/// workspace can be published independently.)
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Manifest {
    /// Publish slug — `"author/name"`. `None` until the workspace
    /// becomes publishable.
    pub name: Option<String>,
    /// One-line description shown in the hub listing. Empty string
    /// when unset; the publish path bails with a clear error if
    /// empty at publish time.
    #[serde(default)]
    pub description: String,
    /// Hub category — matches the `category` segment on the listing
    /// surface. Empty string when unset; lowercase kebab-case,
    /// validated server-side at publish time.
    #[serde(default)]
    pub category: String,
    /// Search tags. Empty list when unset.
    #[serde(default)]
    pub tags: Vec<String>,
    /// Map from `"author/slug"` to integer hub version. Optional on
    /// parse because a workspace without deps is common.
    #[serde(default)]
    pub deps: BTreeMap<String, u32>,
}

#[derive(Debug, Error)]
pub enum ManifestError {
    #[error("manifest is not valid TOML: {0}")]
    Toml(#[from] toml::de::Error),
    #[error("manifest serialization failed: {0}")]
    Serialize(#[from] toml::ser::Error),
}

pub fn parse_manifest(src: &str) -> Result<Manifest, ManifestError> {
    let m: Manifest = toml::from_str(src)?;
    Ok(m)
}

pub fn serialize_manifest(m: &Manifest) -> Result<String, ManifestError> {
    let s = toml::to_string_pretty(m)?;
    Ok(s)
}

/// `forage.lock` shape. One per workspace; generated by `forage update`.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct Lockfile {
    #[serde(default)]
    pub deps: BTreeMap<String, LockedDep>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct LockedDep {
    pub version: u32,
    /// SHA-256 (hex) of the published package, captured at fetch time.
    /// Empty string when the dep was resolved offline against a cached
    /// package that didn't ship a digest — keeps the lockfile populated
    /// for tooling that just wants version pinning.
    #[serde(default)]
    pub hash: String,
}

pub fn parse_lockfile(src: &str) -> Result<Lockfile, ManifestError> {
    let l: Lockfile = toml::from_str(src)?;
    Ok(l)
}

pub fn serialize_lockfile(l: &Lockfile) -> Result<String, ManifestError> {
    let s = toml::to_string_pretty(l)?;
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_manifest_round_trips() {
        // The in-code Default impl emits required fields with their
        // empty values; parsing must succeed because the keys are
        // present.
        let m = Manifest::default();
        let s = serialize_manifest(&m).unwrap();
        let back = parse_manifest(&s).unwrap();
        assert_eq!(m, back);
    }

    #[test]
    fn manifest_with_name_and_deps() {
        let src = r#"
            name = "dima/cannabis"
            description = "Cannabis-domain shared types"
            category = "shared-types"
            tags = ["cannabis"]
            [deps]
            "dima/shared-types" = 3
            "alice/dispensary"  = 1
        "#;
        let m = parse_manifest(src).unwrap();
        assert_eq!(m.name.as_deref(), Some("dima/cannabis"));
        assert_eq!(m.deps.get("dima/shared-types"), Some(&3));
        assert_eq!(m.deps.get("alice/dispensary"), Some(&1));
    }

    #[test]
    fn deps_only_manifest_parses() {
        // Every workspace-loadable manifest must parse, including ones
        // that pre-date the publish-metadata schema. Workspace identity
        // (name, deps) is the load-time concern; publish metadata
        // (description, category, tags) is enforced at publish time.
        let src = r#"
            [deps]
            "dima/shared-types" = 7
        "#;
        let m = parse_manifest(src).unwrap();
        assert!(m.name.is_none());
        assert!(m.description.is_empty());
        assert!(m.category.is_empty());
        assert!(m.tags.is_empty());
        assert_eq!(m.deps.len(), 1);
    }

    #[test]
    fn empty_manifest_parses_with_defaults() {
        let m = parse_manifest("").unwrap();
        assert!(m.name.is_none());
        assert!(m.description.is_empty());
        assert!(m.category.is_empty());
        assert!(m.tags.is_empty());
        assert!(m.deps.is_empty());
    }

    #[test]
    fn missing_deps_table_defaults_to_empty() {
        let m = parse_manifest("name = \"dima/cannabis\"\n").unwrap();
        assert!(m.deps.is_empty());
    }

    #[test]
    fn lockfile_round_trips() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "dima/shared-types".into(),
            LockedDep {
                version: 3,
                hash: "deadbeef".into(),
            },
        );
        let l = Lockfile { deps };
        let s = serialize_lockfile(&l).unwrap();
        let back = parse_lockfile(&s).unwrap();
        assert_eq!(l, back);
    }
}
