//! `forage.toml` parse + serialize.
//!
//! Shape:
//!
//! ```toml
//! # optional — required for `forage publish`.
//! name = "dima/cannabis"
//!
//! [deps]
//! "dima/shared-types" = 3
//! ```
//!
//! The lockfile (`forage.lock`) reuses the same TOML wire format with a
//! `[deps]` table whose values are `{ version, hash }` records — see
//! `Lockfile` / `LockedDep` below.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use ts_rs::TS;

/// `forage.toml` shape. Every field declared without `#[serde(default)]`
/// is required on parse — a manifest that omits `description`,
/// `category`, or `tags` is malformed and fails to load. New
/// workspaces created in-code use the `Default` impl, which serialises
/// to a manifest where all required fields are present (with empty
/// string / empty list values); the round-trip succeeds because the
/// keys are emitted, just empty.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Manifest {
    /// Publish slug — `"author/name"`. `None` until the workspace
    /// becomes publishable.
    pub name: Option<String>,
    /// One-line description shown in the hub listing. Required on
    /// parse; the publish path enforces a non-empty value (per the
    /// hub-api shape).
    pub description: String,
    /// Hub category — matches the `category` segment on the listing
    /// surface. Required on parse; lowercase kebab-case, validated
    /// server-side.
    pub category: String,
    /// Search tags. Required on parse; empty list when unset.
    pub tags: Vec<String>,
    /// Map from `"author/slug"` to integer hub version. Optional on
    /// parse because a workspace without deps is common.
    #[serde(default)]
    pub deps: BTreeMap<String, u32>,
}

#[derive(Debug, Error)]
pub enum ManifestError {
    #[error("manifest is not valid TOML: {0}")]
    Toml(#[from] toml::de::Error),
    #[error("manifest serialization failed: {0}")]
    Serialize(#[from] toml::ser::Error),
}

pub fn parse_manifest(src: &str) -> Result<Manifest, ManifestError> {
    let m: Manifest = toml::from_str(src)?;
    Ok(m)
}

pub fn serialize_manifest(m: &Manifest) -> Result<String, ManifestError> {
    let s = toml::to_string_pretty(m)?;
    Ok(s)
}

/// `forage.lock` shape. One per workspace; generated by `forage update`.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct Lockfile {
    #[serde(default)]
    pub deps: BTreeMap<String, LockedDep>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct LockedDep {
    pub version: u32,
    /// SHA-256 (hex) of the published package, captured at fetch time.
    /// Empty string when the dep was resolved offline against a cached
    /// package that didn't ship a digest — keeps the lockfile populated
    /// for tooling that just wants version pinning.
    #[serde(default)]
    pub hash: String,
}

pub fn parse_lockfile(src: &str) -> Result<Lockfile, ManifestError> {
    let l: Lockfile = toml::from_str(src)?;
    Ok(l)
}

pub fn serialize_lockfile(l: &Lockfile) -> Result<String, ManifestError> {
    let s = toml::to_string_pretty(l)?;
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_manifest_round_trips() {
        // The in-code Default impl emits required fields with their
        // empty values; parsing must succeed because the keys are
        // present.
        let m = Manifest::default();
        let s = serialize_manifest(&m).unwrap();
        let back = parse_manifest(&s).unwrap();
        assert_eq!(m, back);
    }

    #[test]
    fn manifest_with_name_and_deps() {
        let src = r#"
            name = "dima/cannabis"
            description = "Cannabis-domain shared types"
            category = "shared-types"
            tags = ["cannabis"]
            [deps]
            "dima/shared-types" = 3
            "alice/dispensary"  = 1
        "#;
        let m = parse_manifest(src).unwrap();
        assert_eq!(m.name.as_deref(), Some("dima/cannabis"));
        assert_eq!(m.deps.get("dima/shared-types"), Some(&3));
        assert_eq!(m.deps.get("alice/dispensary"), Some(&1));
    }

    #[test]
    fn deps_only_manifest_parses() {
        // `name` is the only field that's actually optional on parse —
        // a workspace can carry [deps] without being publishable.
        // `description`, `category`, `tags` are required.
        let src = r#"
            description = ""
            category = ""
            tags = []
            [deps]
            "dima/shared-types" = 7
        "#;
        let m = parse_manifest(src).unwrap();
        assert!(m.name.is_none());
        assert_eq!(m.deps.len(), 1);
    }

    #[test]
    fn missing_deps_table_defaults_to_empty() {
        let m = parse_manifest(
            "name = \"dima/cannabis\"\ndescription = \"x\"\ncategory = \"x\"\ntags = []\n",
        )
        .unwrap();
        assert!(m.deps.is_empty());
    }

    #[test]
    fn missing_required_fields_fail_to_parse() {
        // Greenfield rule: no `#[serde(default)]` on description /
        // category / tags. A manifest that omits them is malformed.
        assert!(parse_manifest("name = \"x/y\"\n").is_err());
        assert!(parse_manifest("description = \"x\"\n").is_err());
        assert!(
            parse_manifest("description = \"x\"\ncategory = \"y\"\n").is_err()
        );
    }

    #[test]
    fn lockfile_round_trips() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "dima/shared-types".into(),
            LockedDep {
                version: 3,
                hash: "deadbeef".into(),
            },
        );
        let l = Lockfile { deps };
        let s = serialize_lockfile(&l).unwrap();
        let back = parse_lockfile(&s).unwrap();
        assert_eq!(l, back);
    }
}
